# Generated by Django 5.0.6 on 2024-05-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
